name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/easydose/c30540c2290c .
        echo ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }} | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/easydose/c30540c2290c

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy easydose-server --image gcr.io/easydose/c30540c2290c --platform managed
